apiVersion: apps/v1
kind: Deployment
metadata:
  name: securityrol-deployment
  namespace: mesh-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securityrol
  template:
    metadata:
      labels:
        app: securityrol
    spec:
      containers:
      - name: securityrol
        image: securityrol-service
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: securityrol-service
  namespace: mesh-apps
spec:
  selector:
    app: securityrol
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
