apiVersion: apps/v1
kind: Deployment
metadata:
  name: solicitude-deployment
  namespace: mesh-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solicitude
  template:
    metadata:
      labels:
        app: solicitude
    spec:
      containers:
      - name: solicitude
        image: solicitude-service
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: solicitude-service
  namespace: mesh-apps
spec:
  selector:
    app: solicitude
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
